const mongoose = require("mongoose");
const Doctor = require("./models/Doctor");
require("dotenv").config();

const mockDoctors = [
  {
    name: "Dr. Priya Sharma",
    specialty: "Cardiologist",
    experience: "14 Years",
    fees: "INR 1200",
    image: "https://i.pravatar.cc/150?img=47",
    availableTimes: ["09:30 AM", "11:00 AM", "02:00 PM", "05:00 PM"],
    city: "Bengaluru",
    hospital: "Manipal Hospital, Old Airport Road",
    languages: ["English", "Hindi", "Kannada"],
    consultationMode: ["Clinic", "Video"],
    rating: 4.8,
    bio: "Specialist in preventive cardiology and hypertension management.",
  },
  {
    name: "Dr. Arjun Menon",
    specialty: "Neurologist",
    experience: "17 Years",
    fees: "INR 1500",
    image: "https://i.pravatar.cc/150?img=59",
    availableTimes: ["10:00 AM", "12:30 PM", "03:30 PM", "06:00 PM"],
    city: "Mumbai",
    hospital: "Kokilaben Dhirubhai Ambani Hospital",
    languages: ["English", "Hindi", "Malayalam"],
    consultationMode: ["Clinic", "Video"],
    rating: 4.7,
    bio: "Experienced in migraine, epilepsy and stroke rehabilitation care.",
  },
  {
    name: "Dr. Neha Reddy",
    specialty: "Dermatologist",
    experience: "9 Years",
    fees: "INR 900",
    image: "https://i.pravatar.cc/150?img=45",
    availableTimes: ["09:00 AM", "11:30 AM", "01:30 PM", "04:30 PM"],
    city: "Hyderabad",
    hospital: "Apollo Hospitals, Jubilee Hills",
    languages: ["English", "Hindi", "Telugu"],
    consultationMode: ["Clinic", "Video"],
    rating: 4.6,
    bio: "Focused on acne, pigmentation and chronic skin condition care.",
  },
  {
    name: "Dr. Kavita Iyer",
    specialty: "General Physician",
    experience: "12 Years",
    fees: "INR 700",
    image: "https://i.pravatar.cc/150?img=32",
    availableTimes: ["08:30 AM", "10:30 AM", "01:00 PM", "07:00 PM"],
    city: "Chennai",
    hospital: "Fortis Malar Hospital",
    languages: ["English", "Tamil", "Hindi"],
    consultationMode: ["Clinic", "Video", "Home Visit"],
    rating: 4.7,
    bio: "Primary care expert for routine checkups and lifestyle disease support.",
  },
  {
    name: "Dr. Rohit Kulkarni",
    specialty: "Orthopedic",
    experience: "11 Years",
    fees: "INR 1100",
    image: "https://i.pravatar.cc/150?img=13",
    availableTimes: ["09:00 AM", "12:00 PM", "04:00 PM", "06:30 PM"],
    city: "Pune",
    hospital: "Ruby Hall Clinic",
    languages: ["English", "Hindi", "Marathi"],
    consultationMode: ["Clinic", "Video"],
    rating: 4.5,
    bio: "Specializes in sports injuries and joint pain management.",
  },
  {
    name: "Dr. Aisha Khan",
    specialty: "Pediatrician",
    experience: "10 Years",
    fees: "INR 850",
    image: "https://i.pravatar.cc/150?img=44",
    availableTimes: ["09:30 AM", "11:00 AM", "02:30 PM", "05:30 PM"],
    city: "Delhi",
    hospital: "Max Super Speciality Hospital, Saket",
    languages: ["English", "Hindi", "Urdu"],
    consultationMode: ["Clinic", "Video"],
    rating: 4.8,
    bio: "Known for child nutrition and respiratory care.",
  },
  {
    name: "Dr. Siddharth Rao",
    specialty: "Endocrinologist",
    experience: "13 Years",
    fees: "INR 1300",
    image: "https://i.pravatar.cc/150?img=52",
    availableTimes: ["10:00 AM", "12:00 PM", "03:00 PM", "06:00 PM"],
    city: "Bengaluru",
    hospital: "Aster CMI Hospital",
    languages: ["English", "Hindi", "Kannada"],
    consultationMode: ["Clinic", "Video"],
    rating: 4.7,
    bio: "Diabetes and thyroid specialist with preventive care programs.",
  },
  {
    name: "Dr. Meera Banerjee",
    specialty: "Gynecologist",
    experience: "16 Years",
    fees: "INR 1400",
    image: "https://i.pravatar.cc/150?img=25",
    availableTimes: ["09:00 AM", "11:30 AM", "02:00 PM", "05:00 PM"],
    city: "Kolkata",
    hospital: "AMRI Hospital, Dhakuria",
    languages: ["English", "Hindi", "Bengali"],
    consultationMode: ["Clinic", "Video"],
    rating: 4.9,
    bio: "Women's health specialist focused on preventive and fertility care.",
  },
  {
    name: "Dr. Harpreet Singh",
    specialty: "Pulmonologist",
    experience: "15 Years",
    fees: "INR 1250",
    image: "https://i.pravatar.cc/150?img=68",
    availableTimes: ["08:30 AM", "10:30 AM", "01:30 PM", "04:30 PM"],
    city: "Chandigarh",
    hospital: "Fortis Hospital, Mohali",
    languages: ["English", "Hindi", "Punjabi"],
    consultationMode: ["Clinic", "Video", "Home Visit"],
    rating: 4.6,
    bio: "Treats asthma, allergies and chronic respiratory conditions.",
  },
  {
    name: "Dr. Nitin Joshi",
    specialty: "Psychiatrist",
    experience: "12 Years",
    fees: "INR 1000",
    image: "https://i.pravatar.cc/150?img=62",
    availableTimes: ["10:30 AM", "12:30 PM", "03:30 PM", "07:00 PM"],
    city: "Jaipur",
    hospital: "EHCC Hospital",
    languages: ["English", "Hindi"],
    consultationMode: ["Clinic", "Video"],
    rating: 4.5,
    bio: "Supports anxiety, sleep disorders and stress management.",
  },
  {
    name: "Dr. Anjali Deshmukh",
    specialty: "Ophthalmologist",
    experience: "14 Years",
    fees: "INR 950",
    image: "https://i.pravatar.cc/150?img=26",
    availableTimes: ["09:30 AM", "11:30 AM", "02:30 PM", "05:30 PM"],
    city: "Nagpur",
    hospital: "Wockhardt Super Speciality Hospital",
    languages: ["English", "Hindi", "Marathi"],
    consultationMode: ["Clinic", "Video"],
    rating: 4.7,
    bio: "Comprehensive eye care including glaucoma and retina screening.",
  },
  {
    name: "Dr. Rohan Sinha",
    specialty: "Gastroenterologist",
    experience: "13 Years",
    fees: "INR 1350",
    image: "https://i.pravatar.cc/150?img=53",
    availableTimes: ["09:00 AM", "11:00 AM", "03:00 PM", "06:30 PM"],
    city: "Lucknow",
    hospital: "Medanta Lucknow",
    languages: ["English", "Hindi"],
    consultationMode: ["Clinic", "Video"],
    rating: 4.6,
    bio: "Specialist in digestive disorders, fatty liver and gut health plans.",
  },
  {
    name: "Dr. Sneha Patil",
    specialty: "ENT Specialist",
    experience: "10 Years",
    fees: "INR 900",
    image: "https://i.pravatar.cc/150?img=34",
    availableTimes: ["08:30 AM", "10:30 AM", "01:00 PM", "05:00 PM"],
    city: "Nashik",
    hospital: "Sahyadri Super Speciality Hospital",
    languages: ["English", "Hindi", "Marathi"],
    consultationMode: ["Clinic", "Video"],
    rating: 4.5,
    bio: "Treats sinus, throat and hearing conditions with preventive care guidance.",
  },
  {
    name: "Dr. Vivek Nair",
    specialty: "Nephrologist",
    experience: "18 Years",
    fees: "INR 1600",
    image: "https://i.pravatar.cc/150?img=57",
    availableTimes: ["09:30 AM", "12:00 PM", "03:30 PM", "06:00 PM"],
    city: "Kochi",
    hospital: "Aster Medcity",
    languages: ["English", "Hindi", "Malayalam"],
    consultationMode: ["Clinic", "Video"],
    rating: 4.8,
    bio: "Kidney care expert focusing on CKD prevention and dialysis follow-up.",
  },
  {
    name: "Dr. Pooja Gupta",
    specialty: "Oncologist",
    experience: "16 Years",
    fees: "INR 1800",
    image: "https://i.pravatar.cc/150?img=29",
    availableTimes: ["10:00 AM", "01:00 PM", "04:00 PM", "06:30 PM"],
    city: "Ahmedabad",
    hospital: "HCG Cancer Centre",
    languages: ["English", "Hindi", "Gujarati"],
    consultationMode: ["Clinic", "Video"],
    rating: 4.7,
    bio: "Comprehensive cancer care with treatment counseling and survivorship planning.",
  },
  {
    name: "Dr. Imran Qureshi",
    specialty: "Urologist",
    experience: "12 Years",
    fees: "INR 1150",
    image: "https://i.pravatar.cc/150?img=64",
    availableTimes: ["09:00 AM", "11:30 AM", "02:30 PM", "06:00 PM"],
    city: "Bhopal",
    hospital: "Chirayu Medical College and Hospital",
    languages: ["English", "Hindi", "Urdu"],
    consultationMode: ["Clinic", "Video"],
    rating: 4.6,
    bio: "Handles urinary disorders, kidney stones and prostate care.",
  },
  {
    name: "Dr. Lakshmi Narayanan",
    specialty: "Rheumatologist",
    experience: "14 Years",
    fees: "INR 1300",
    image: "https://i.pravatar.cc/150?img=23",
    availableTimes: ["08:30 AM", "11:00 AM", "02:00 PM", "05:30 PM"],
    city: "Coimbatore",
    hospital: "KMCH Hospital",
    languages: ["English", "Tamil", "Hindi"],
    consultationMode: ["Clinic", "Video"],
    rating: 4.7,
    bio: "Autoimmune and arthritis specialist for long term pain and mobility management.",
  },
  {
    name: "Dr. Tenzin Dorjee",
    specialty: "Psychologist",
    experience: "9 Years",
    fees: "INR 850",
    image: "https://i.pravatar.cc/150?img=33",
    availableTimes: ["10:00 AM", "12:00 PM", "03:00 PM", "07:00 PM"],
    city: "Delhi",
    hospital: "Mind Wellness Centre",
    languages: ["English", "Hindi"],
    consultationMode: ["Video", "Clinic"],
    rating: 4.5,
    bio: "Offers therapy for anxiety, burnout and emotional resilience.",
  },
  {
    name: "Dr. Farah Siddiqui",
    specialty: "Diabetologist",
    experience: "11 Years",
    fees: "INR 1000",
    image: "https://i.pravatar.cc/150?img=30",
    availableTimes: ["09:30 AM", "11:30 AM", "02:30 PM", "06:30 PM"],
    city: "Indore",
    hospital: "Bombay Hospital Indore",
    languages: ["English", "Hindi"],
    consultationMode: ["Clinic", "Video", "Home Visit"],
    rating: 4.6,
    bio: "Diabetes reversal lifestyle programs and insulin optimization support.",
  },
  {
    name: "Dr. Karanvir Gill",
    specialty: "Sports Medicine",
    experience: "8 Years",
    fees: "INR 950",
    image: "https://i.pravatar.cc/150?img=67",
    availableTimes: ["08:00 AM", "10:00 AM", "01:00 PM", "05:00 PM"],
    city: "Bengaluru",
    hospital: "Sparsh Hospital",
    languages: ["English", "Hindi", "Punjabi"],
    consultationMode: ["Clinic", "Video"],
    rating: 4.4,
    bio: "Rehabilitation and injury prevention for runners and athletes.",
  }
];

mongoose
  .connect(process.env.MONGODB_URI)
  .then(async () => {
    console.log("Connected to MongoDB");
    // Clear existing docs
    await Doctor.deleteMany({});
    console.log("Cleared existing doctors");
    
    // Insert Mock Data
    await Doctor.insertMany(mockDoctors);
    console.log("Inserted mock doctors successfully");
    
    mongoose.disconnect();
  })
  .catch((err) => {
    console.error("Database connection failed", err);
    process.exit(1);
  });
